[#31] Fix error message printing
reduct-storage/reduct-py pull request #32
Opened 2022-07-07 19:55 UTC by aschenbecherwespe

Also remove an unneeded default asignment and unneeded linter disable

2022-07-08 21:36 UTC, flipback requested changes
Looks great! Only two things:
1. CHANGELOG.md
2.  I think we can add a test.

2022-07-08 21:47 UTC, flipback requested changes

2022-07-08 21:47 UTC, flipback commented on pkg/reduct/error.py
>          self._detail = message
Looks like unused

2022-07-08 21:47 UTC, aschenbecherwespe commented
Create a new test?

2022-07-08 21:50 UTC, aschenbecherwespe commented on pkg/reduct/error.py
>          self._detail = message
Yeah, I'm not sure. Are any of these used internally by python?

2022-07-08 21:57 UTC, flipback commented on pkg/reduct/error.py
>          self._detail = message
I think not.

2022-07-08 22:43 UTC, aschenbecherwespe commented on pkg/reduct/error.py
>          self._detail = message
okay removed

2022-07-09 06:33 UTC, flipback approved these changes

2022-07-09 06:33 UTC, merged